# Umræður

## Kafbáturinn
Kafbáturinn tekur upp myndefni af miklum gæðum og er stöðugur á siglingu. Rannsakendur eiga gott með að greina tegundir út frá myndefninu. Myndefnið hefur vakið áhuga annara rannsakenda í skyldum verkefnum. Fyrir utan bilun sem orsakaðist af framleiðslugalla hefur hann mætt okkar vonum og gott betur.

## Mat á stærð þaraskóga m.t.t. nýtingar
Mat á stærð skóganna verður áætlað eftir megni en skógurinn milli Eyrarinnar og Skeljatanga (sk1) er um 0,5 km^2^

## Seinkanir og áframhaldandi sýnatökur
Sumarið 2018 var óvenjulegt af því leyti að við vorum fámönnuð. Rannsóknabáturinn okkar var mikið í öðrum verkefnum og þess utan var rigningasamt þannig að ekki var gott að vera úti við með raftæki (en fjarstýringin af kafbátnum er venjuleg spjaldtölva). Við hjá BioPol höfum metnað fyrir því að klára þetta verkefni og fengum eins árs frest til að skila af okkur lokaskýrslu og því er rannsóknum haldið áfram sumarið 2019.  Kafbátnum er að mestu stýrt úr Zodiac gúmmíbáti. Sýnatökustaðir af svæðum þar sem forkönnun hefur ekki farið fram (innan við Ytriey og Vatnsnes) verður gerð eftir samráði við gamla grásleppukarla af svæðinu en veiðiaðferðir þeirra voru á þann máta að vitneskja um þaraskóga var þeim nauðsynleg áður fyrr og því geta þeir bent á áhugaverðustu svæðin.